#!/usr/bin/env bash

export CC=clang
export CXX=clang++

if [ -d "./build" ]; then
    rm -rf ./build
fi


mkdir ./build
cd ./build
reset && \
echo "In Directory: "`pwd`
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DCOMPILER=LLVM -DSTANDARD=11 ..  && \
make && \
cp ./compile_commands.json ../
